# Generated by Django 5.2.7 on 2026-01-02 15:22

import attendance.models
import django.core.validators
import django.db.models.deletion
import uuid_utils._uuid_utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "academic_year_id",
                    attendance.models.UUIDv7Field(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("academic_start_year", models.CharField(max_length=10)),
                ("academic_end_year", models.CharField(max_length=10)),
                ("academic_year_active_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "academic_year",
                "ordering": ["-academic_start_year"],
                "unique_together": {("academic_start_year", "academic_end_year")},
            },
        ),
        migrations.CreateModel(
            name="Class",
            fields=[
                (
                    "class_id",
                    attendance.models.UUIDv7Field(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("class_name", models.CharField(max_length=50)),
                ("grade_level", models.IntegerField()),
                (
                    "homeroom_teacher",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="attendance.academicyear",
                    ),
                ),
            ],
            options={
                "db_table": "class",
                "ordering": ["grade_level", "class_name"],
                "unique_together": {("class_name", "academic_year")},
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "student_id",
                    attendance.models.UUIDv7Field(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "student_card_uid",
                    models.CharField(db_index=True, max_length=8, unique=True),
                ),
                ("student_full_name", models.CharField(max_length=150)),
                (
                    "student_gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("student_birthday", models.DateField(blank=True, null=True)),
                (
                    "student_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-11 digit phone number",
                                regex="^\\d{10,11}$",
                            )
                        ],
                    ),
                ),
                (
                    "student_regular_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_temporary_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "student_profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=attendance.models.student_profile_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("student_active_status", models.BooleanField(default=True)),
                (
                    "student_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="students",
                        to="attendance.class",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["student_full_name"],
            },
        ),
        migrations.CreateModel(
            name="Parents",
            fields=[
                (
                    "parent_id",
                    attendance.models.UUIDv7Field(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "parent_mother_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "parent_mother_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-11 digit phone number",
                                regex="^\\d{10,11}$",
                            )
                        ],
                    ),
                ),
                ("parent_mother_birthday", models.DateField(blank=True, null=True)),
                (
                    "parent_mother_job",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "parent_mother_workplace",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parent_father_name",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "parent_father_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-11 digit phone number",
                                regex="^\\d{10,11}$",
                            )
                        ],
                    ),
                ),
                ("parent_father_birthday", models.DateField(blank=True, null=True)),
                (
                    "parent_father_job",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                (
                    "parent_father_workplace",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parent_regular_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "parent_temporary_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parents",
                        to="attendance.students",
                    ),
                ),
            ],
            options={
                "db_table": "parents",
            },
        ),
        migrations.CreateModel(
            name="Attendance",
            fields=[
                (
                    "attendance_id",
                    attendance.models.UUIDv7Field(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("check_in_time", models.DateTimeField(auto_now_add=True)),
                ("check_in_date", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("attended", "Đã điểm danh"),
                            ("late", "Trễ"),
                            ("absent", "Vắng"),
                        ],
                        default="absent",
                        max_length=20,
                    ),
                ),
                (
                    "scanned_card_uid",
                    models.CharField(blank=True, max_length=8, null=True),
                ),
                ("device_id", models.CharField(blank=True, max_length=50, null=True)),
                ("is_verified_by_teacher", models.BooleanField(default=False)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="attendance.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="attendance.students",
                    ),
                ),
            ],
            options={
                "db_table": "attendance",
                "ordering": ["-check_in_time"],
            },
        ),
        migrations.CreateModel(
            name="Teachers",
            fields=[
                (
                    "teacher_id",
                    attendance.models.UUIDv7Field(
                        default=uuid_utils._uuid_utils.uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("teacher_full_name", models.CharField(max_length=150)),
                (
                    "teacher_gender",
                    models.CharField(
                        blank=True,
                        choices=[("male", "Nam"), ("female", "Nữ"), ("other", "Khác")],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("teacher_birthday", models.DateField(blank=True, null=True)),
                (
                    "teacher_phone_number",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Enter a valid 10-11 digit phone number",
                                regex="^\\d{10,11}$",
                            )
                        ],
                    ),
                ),
                (
                    "teacher_regular_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "teacher_temporary_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "teacher_profile_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=attendance.models.teacher_profile_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("teacher_active_status", models.BooleanField(default=True)),
                (
                    "teacher_class",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="teachers",
                        to="attendance.class",
                    ),
                ),
            ],
            options={
                "db_table": "teachers",
                "ordering": ["teacher_full_name"],
            },
        ),
        migrations.AddIndex(
            model_name="students",
            index=models.Index(
                fields=["student_card_uid"], name="students_student_52e006_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="students",
            index=models.Index(
                fields=["student_active_status"], name="students_student_2b50e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["check_in_date"], name="attendance_check_i_1c3b81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "check_in_date"],
                name="attendance_student_53c2e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["is_verified_by_teacher"], name="attendance_is_veri_7dfc66_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("student", "check_in_date")},
        ),
    ]
