# Generated by Django 5.2.7 on 2026-01-02 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={
                "ordering": ["grade_level", "class_name"],
                "verbose_name": "Class",
                "verbose_name_plural": "Classes",
            },
        ),
        migrations.AlterModelOptions(
            name="parents",
            options={"verbose_name": "Parent", "verbose_name_plural": "Parents"},
        ),
        migrations.AlterModelOptions(
            name="students",
            options={
                "ordering": ["student_full_name"],
                "verbose_name": "Student",
                "verbose_name_plural": "Students",
            },
        ),
        migrations.AlterModelOptions(
            name="teachers",
            options={
                "ordering": ["teacher_full_name"],
                "verbose_name": "Teacher",
                "verbose_name_plural": "Teachers",
            },
        ),
    ]
