# Generated by Django 5.2.7 on 2026-01-02 15:46

import attendance.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_class_options_alter_parents_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="academic_year_id",
            field=attendance.models.UUIDv7Field(
                default=attendance.models.generate_uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="attendance_id",
            field=attendance.models.UUIDv7Field(
                default=attendance.models.generate_uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="class",
            name="class_id",
            field=attendance.models.UUIDv7Field(
                default=attendance.models.generate_uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="parents",
            name="parent_id",
            field=attendance.models.UUIDv7Field(
                default=attendance.models.generate_uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="students",
            name="student_id",
            field=attendance.models.UUIDv7Field(
                default=attendance.models.generate_uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="teacher_id",
            field=attendance.models.UUIDv7Field(
                default=attendance.models.generate_uuid7,
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
