# Generated by Django 5.2.7 on 2026-01-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_alter_academicyear_academic_year_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="homeroom_teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="homeroom_classes",
                to="attendance.teachers",
            ),
        ),
    ]
