# Generated by Django 5.2.7 on 2026-01-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0004_alter_class_homeroom_teacher"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="teacher_card_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
