# Generated by Django 5.2.7 on 2026-01-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0005_teachers_teacher_card_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachers",
            name="teacher_card_id",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
