# Generated by Django 5.2.7 on 2026-01-02 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0006_alter_teachers_teacher_card_id"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="class",
            unique_together={
                ("class_name", "academic_year"),
                ("homeroom_teacher", "academic_year"),
            },
        ),
    ]
