# Generated by Django 5.2.7 on 2026-01-04 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0008_parents_user_teachers_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="parents",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parent_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="teachers",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(fields=["status"], name="attendance_status_a068a7_idx"),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["check_in_date", "status"], name="attendance_check_i_865653_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendance",
            index=models.Index(
                fields=["student", "check_in_date", "status"],
                name="attendance_student_6d76da_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="students",
            index=models.Index(
                fields=["student_class"], name="students_student_7de3b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="students",
            index=models.Index(
                fields=["student_full_name"], name="students_student_84790f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachers",
            index=models.Index(
                fields=["teacher_card_id"], name="teachers_teacher_57b5bd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="teachers",
            index=models.Index(
                fields=["teacher_active_status"], name="teachers_teacher_56c2e0_idx"
            ),
        ),
    ]
