# Generated by Django 5.2.7 on 2026-01-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0009_alter_parents_user_alter_teachers_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="check_in_date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in_time",
            field=models.DateTimeField(),
        ),
    ]
