# Generated by Django 5.2.7 on 2026-01-09 12:55

import attendance.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0010_alter_attendance_check_in_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendancePeriod",
            fields=[
                (
                    "period_attendance_id",
                    attendance.models.UUIDv7Field(
                        default=attendance.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_number", models.IntegerField()),
                ("subject_name", models.CharField(max_length=100)),
                ("period_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Có mặt"),
                            ("absent", "Vắng"),
                            ("late", "Trễ"),
                            ("excused", "Có phép"),
                            ("sneaked_out", "Trốn học"),
                        ],
                        default="present",
                        max_length=20,
                    ),
                ),
                ("marked_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "attendance_periods",
                "ordering": ["period_date", "period_number"],
            },
        ),
        migrations.CreateModel(
            name="ClassSchedule",
            fields=[
                (
                    "schedule_id",
                    attendance.models.UUIDv7Field(
                        default=attendance.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (1, "Thứ Hai"),
                            (2, "Thứ Ba"),
                            (3, "Thứ Tư"),
                            (4, "Thứ Năm"),
                            (5, "Thứ Sáu"),
                            (6, "Thứ Bảy"),
                        ]
                    ),
                ),
                ("subject_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "class_schedules",
                "ordering": ["day_of_week", "period__period_number"],
            },
        ),
        migrations.CreateModel(
            name="ExcusedAbsence",
            fields=[
                (
                    "excuse_id",
                    attendance.models.UUIDv7Field(
                        default=attendance.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "absence_type",
                    models.CharField(
                        choices=[
                            ("full_day", "Cả ngày"),
                            ("morning", "Buổi sáng"),
                            ("afternoon", "Buổi chiều"),
                            ("specific_periods", "Tiết cụ thể"),
                        ],
                        default="full_day",
                        max_length=20,
                    ),
                ),
                (
                    "specific_periods",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("reason", models.TextField()),
                ("approved_by_homeroom", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent_contact_method",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "excused_absences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="SchoolPeriod",
            fields=[
                (
                    "period_id",
                    attendance.models.UUIDv7Field(
                        default=attendance.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("period_number", models.IntegerField(unique=True)),
                ("period_name", models.CharField(max_length=50)),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "school_periods",
                "ordering": ["period_number"],
            },
        ),
        migrations.AlterModelOptions(
            name="attendance",
            options={"ordering": ["-check_in_date"]},
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance_is_veri_7dfc66_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance_check_i_865653_idx",
        ),
        migrations.RemoveIndex(
            model_name="attendance",
            name="attendance_student_6d76da_idx",
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="attendance",
            name="afternoon_gate_scan_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="afternoon_scanned_card_uid",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="morning_gate_scan_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attendance",
            name="morning_scanned_card_uid",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name="students",
            name="seat_number",
            field=models.IntegerField(
                blank=True, help_text="Seat in tổ (1-10)", null=True
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="student_role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("student", "Học sinh"),
                    ("lop_truong", "Lớp trưởng"),
                    ("lop_pho", "Lớp phó"),
                    ("to_truong", "Tổ trưởng"),
                ],
                default="student",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="students",
            name="to_number",
            field=models.IntegerField(
                blank=True, help_text="Tổ number (1-4)", null=True
            ),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="check_in_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("attended", "Đã điểm danh"),
                    ("late", "Trễ"),
                    ("absent", "Vắng"),
                    ("scanned_morning", "Đã quét buổi sáng"),
                    ("scanned_afternoon", "Đã quét buổi chiều"),
                    ("scanned_both", "Đã quét cả 2 buổi"),
                    ("no_scan", "Chưa quét"),
                    ("late_arrival", "Đến trễ"),
                ],
                default="absent",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="students",
            index=models.Index(
                fields=["student_role"], name="students_student_a8d553_idx"
            ),
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="attendance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_records",
                to="attendance.attendance",
            ),
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="marked_by_teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="marked_periods",
                to="attendance.teachers",
            ),
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_attendances",
                to="attendance.students",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="academic_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="attendance.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="class_obj",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="attendance.class",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="teacher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teaching_schedules",
                to="attendance.teachers",
            ),
        ),
        migrations.AddField(
            model_name="attendanceperiod",
            name="schedule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_records",
                to="attendance.classschedule",
            ),
        ),
        migrations.AddField(
            model_name="excusedabsence",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="excused_absences",
                to="attendance.students",
            ),
        ),
        migrations.AddField(
            model_name="classschedule",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schedules",
                to="attendance.schoolperiod",
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceperiod",
            index=models.Index(
                fields=["period_date"], name="attendance__period__cf4364_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceperiod",
            index=models.Index(
                fields=["student", "period_date"], name="attendance__student_da2c1a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="attendanceperiod",
            index=models.Index(fields=["status"], name="attendance__status_e83807_idx"),
        ),
        migrations.AddIndex(
            model_name="attendanceperiod",
            index=models.Index(
                fields=["marked_by_teacher"], name="attendance__marked__cdce58_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendanceperiod",
            unique_together={("student", "period_date", "period_number")},
        ),
        migrations.AddIndex(
            model_name="excusedabsence",
            index=models.Index(
                fields=["student", "start_date", "end_date"],
                name="excused_abs_student_4c9cac_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="classschedule",
            unique_together={("class_obj", "academic_year", "day_of_week", "period")},
        ),
    ]
