# Generated by Django 5.2.7 on 2026-01-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0011_attendanceperiod_classschedule_excusedabsence_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachers",
            name="teacher_subject",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
