# Generated by Django 5.2.7 on 2026-01-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0012_teachers_teacher_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachers",
            name="teacher_subject",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
