# Generated by Django 5.2.7 on 2026-01-09 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0013_alter_teachers_teacher_subject"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teachers",
            name="teacher_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="teachers",
                to="attendance.class",
            ),
        ),
    ]
