# Generated by Django 5.2.7 on 2026-01-09 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0014_alter_teachers_teacher_class"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachers",
            name="teacher_class",
        ),
    ]
