# Generated by Django 5.2.7 on 2026-01-11 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0015_remove_teachers_teacher_class"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendanceperiod",
            name="attendance",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="period_records",
                to="attendance.attendance",
            ),
        ),
    ]
